import enum


class TokenType(enum.Enum):
    EOF = "\0"
    NEWLINE = "\n"
    NUMBER = "NUMBER"
    IDENT = "IDENT"
    STRING = "STRING"
    # Keywords
    VAR_ASSIGN = "var"
    IF = "if"
    FUNCTION_DEFINE = "func"
    ELSE = "else"
    ELSEIF = "elseif"
    THEN = "{"
    END = "}"
    WHILE = "while"
    REPEAT = "repeat"
    EACH = "each"
    IN = "in"
    RETURN = "return"
    # Operators.
    EQ = "="
    PLUS = "+"
    PLUSEQ = "+="
    ASTERISKEQ = "*="
    MINUSEQ = "-="
    SLASHEQ = "/="
    MINUS = "-"
    ASTERISK = "*"
    SLASH = "/"
    PLUSPLUS = "++"
    MINUSMINUS = "--"
    EQEQ = "=="
    NOTEQ = "!="
    LT = "<"
    LTEQ = "<="
    GT = ">"
    GTEQ = ">="
    # Misc
    OPAREN = "("
    CPAREN = ")"
    SEPERATOR = ","
    DOT = "."
    OBRACKET = "["
    CBRACKET = "]"
    COMMENT = "#"
